services:
  nginx:
    build:
      context: ./nginx
    container_name: "nginx_container"
    ports: 
      - "80:00"
    networks: 
      - django-app-network
    restart: always
    depends_on: 
      - django

  db:
    image: mysql
    container_name: "db_container"
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_main
    volumes: 
      - django-app-mysql-volume:/var/lib/mysql
    networks: 
      - django-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: always

  django:
    build:
      context: .
    container_name: "django_container"
    ports: 
      - "8000:8000"
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    networks: 
      - django-app-network
    env_file: 
      - ".env"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    depends_on: 
      - db

volumes:
  django-app-mysql-volume:
  
networks:
  django-app-network: